### ISSUE TITLE
Request validatiion

### ISSUE THREAD

**Issue by robotateme** [XxelTaerg/insure_the_bro#5]
https://github.com/XxelTaerg/insure_the_bro/blob/94d2ef9268b1ecdb5e2c363432b3fd4b3bb6a3b4/insurance/app/Http/Controllers/CustomAuthController.php#L20

 Вынеси валидацию из контроллера в FormRequest.

**Comment by XxelTaerg** [comment]
вынес валидацию из customLogin и customRegistration
